export const data = [
  {
    username: "lise",
    firstName: "Lise",
    lastName: "Otsuki",
    email: "lise.otsuki@gmail.com",
    profileImg: "https://xsgames.co/randomusers/assets/avatars/female/70.jpg",
    department: "engineering",
    userType: "admin",
  },
  {
    username: "tamekia",
    firstName: "Tamekia",
    lastName: "Blazevich",
    email: "tamekia.blazevich@gmail.com",
    profileImg: "https://xsgames.co/randomusers/assets/avatars/female/69.jpg",
    department: "consultanting",
    userType: "employee",
  },
  {
    username: "ranee",
    firstName: "Ranee",
    lastName: "Olari",
    email: "ranee.olari@gmail.com",
    profileImg: "https://xsgames.co/randomusers/assets/avatars/female/68.jpg",
    department: "marketing",
    userType: "employee",
  },
  {
    username: "refugio",
    firstName: "Refugio",
    lastName: "Plotkin",
    email: "refugio.plotkin@gmail.com",
    profileImg: "https://xsgames.co/randomusers/assets/avatars/female/67.jpg",
    department: "engineering",
    userType: "employee",
  },
  {
    username: "sunshine",
    firstName: "Sunshine",
    lastName: "Zukor",
    email: "sunshine.zukor@gmail.com",
    profileImg: "https://xsgames.co/randomusers/assets/avatars/female/66.jpg",
    department: "consultanting",
    userType: "employee",
  },
];
