export const taskData = [
  {
    jobType: "New Project",
    taskList: [
      {
        title: "Final Project : App development",
        type: "Software Development",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "waiting",
        ongoing: false,
        submitted: false,
        submissionDate: null,
      },
      {
        title: "Paper finding : Covid statistics",
        type: "Resarch Methodology",
        date: "Mar 22, 2022",
        priority: "MEDIUM",
        currentState: "waiting",
        ongoing: false,
        submitted: false,
        submissionDate: null,
      },
    ],
  },
  {
    jobType: "In Progress",
    taskList: [
      {
        title: "Final Project : Wordpress website",
        type: "Software Development",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "ongoing",
        ongoing: true,
        submitted: false,
        submissionDate: null,
      },
    ],
  },
  {
    jobType: "Submitted",
    taskList: [
      {
        title: "Final Project : Knowledge management paper",
        type: "Resarch Methodology",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "submitted",
        ongoing: true,
        submitted: false,
        submissionDate: "Feb 21, 2022",
      },
      {
        title: "Exercise : Android XML",
        type: "Software Development",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "submitted",
        ongoing: true,
        submitted: false,
        submissionDate: "Feb 21, 2022",
      },
      {
        title: "Exercise : RESTful vs REST API",
        type: "Collaborative Computing",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "submitted",
        ongoing: true,
        submitted: false,
        submissionDate: "Feb 21, 2022",
      },
    ],
  },
  {
    jobType: "Completed",
    taskList: [
      {
        title: "Project 1 : System Design exercise for “Koki”",
        type: "Collaborative Computing",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "completed",
        ongoing: false,
        submitted: true,
        submissionDate: "Feb 21, 2022",
      },
      {
        title: "Project 2 : Strategic system exercise for “Koki”",
        type: "Resarch Methodology",
        date: "Mar 22, 2022",
        priority: "HIGH",
        currentState: "completed",
        ongoing: false,
        submitted: true,
        submissionDate: "Feb 21, 2022",
      },
    ],
  },
];
